"""Create tasks table1

Revision ID: bece50ec8f24
Revises: f73762ad604e
Create Date: 2025-06-23 19:57:19.106277

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bece50ec8f24'
down_revision: Union[str, Sequence[str], None] = 'f73762ad604e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('user_id', sa.Integer(), nullable=True))
    op.drop_column('tasks', 'userd_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('userd_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('tasks', 'user_id')
    # ### end Alembic commands ###
